name: Orion GYM Pipeline
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  package:
    needs: [lint]
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
        
      - name: Convert to zip
        uses: vimtor/action-zip@v1
        with:
          files: app/build/outputs/apk/debug/Orion-1.0.apk
          dest: result.zip  

      - name: Upload to gdrive
        uses: Jodebu/upload-to-drive@master
        with:
          target: result.zip
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          folder: ${{ secrets.FOLDERID }}
