name: Orion GYM Pipeline
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  package:
    needs: [lint]
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Extract version from tag
        uses: ./

      - name: Output the variables
        run: |
          echo The major was $MAJOR
          echo The minor was $MINOR
          echo The patch was $PATCH
          echo The pre-release was $PRE_RELEASE
          echo The number of commits was $NUMBER_OF_COMMITS
          echo The number of commits since tag was $NUMBER_OF_COMMITS_SINCE_TAG
